name: "GRDB CI"

on:
  push:
    branches: 
      - master
      - development
    paths:
      - 'GRDB/**'
      - 'Tests/**'
      - '.github/workflows/**'
      - 'Package.swift'
  pull_request:
    paths:
      - 'GRDB/**'
      - 'Tests/**'
      - '.github/workflows/**'
      - 'Package.swift'

concurrency: 
  group: ${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  macOS:
    name: Test macOS
    runs-on: ${{ matrix.runsOn }}
    env:
      DEVELOPER_DIR: "/Applications/${{ matrix.xcode }}/Contents/Developer"
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode: "Xcode_13.2.1.app"
            runsOn: macOS-11
            name: "macOS 11, Swift 5.5"
          - xcode: "Xcode_12.5.1.app"
            runsOn: macOS-11
            name: "macOS 11, Swift 5.4"
          - xcode: "Xcode_12.4.app"
            runsOn: macOS-10.15
            name: "macOS 10.15, Swift 5.3"
    steps:
      - uses: actions/checkout@v2
      - name: ${{ matrix.name }}
        run: make test_framework_GRDBOSX_maxSwift
  iOS:
    name: Test iOS
    runs-on: ${{ matrix.runsOn }}
    env:
      DEVELOPER_DIR: "/Applications/${{ matrix.xcode }}/Contents/Developer"
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode: "Xcode_13.2.1.app"
            runsOn: macOS-11
            name: "macOS 11, Swift 5.5"
          - xcode: "Xcode_12.5.1.app"
            runsOn: macOS-11
            name: "macOS 11, Swift 5.4"
          - xcode: "Xcode_12.4.app"
            runsOn: macOS-10.15
            name: "macOS 10.15, Swift 5.3"
    steps:
      - uses: actions/checkout@v2
      - name: ${{ matrix.name }}
        run: make test_framework_GRDBiOS_maxTarget_maxSwift
  iOSMinTarget:
    name: Test iOS minimum target
    runs-on: ${{ matrix.runsOn }}
    env:
      DEVELOPER_DIR: "/Applications/${{ matrix.xcode }}/Contents/Developer"
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode: "Xcode_13.2.1.app"
            runsOn: macOS-11
            name: "macOS 11, Swift 5.5"
          - xcode: "Xcode_12.5.1.app"
            runsOn: macOS-11
            name: "macOS 11, Swift 5.4"
          - xcode: "Xcode_12.4.app"
            runsOn: macOS-10.15
            name: "macOS 10.15, Swift 5.3"
    steps:
      - uses: actions/checkout@v2
      - name: ${{ matrix.name }}
        run: make test_framework_GRDBiOS_minTarget
  SQLCipher3:
    name: Test SQLCipher 3
    runs-on: macOS-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Test SQLCipher 3
        run: make test_framework_SQLCipher3
  SQLCipher4:
    name: Test SQLCipher 4
    runs-on: macOS-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Test SQLCipher 4
        run: make test_framework_SQLCipher4
  SQLiteCustom:
    name: Test custom SQLite build
    runs-on: macOS-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Test custom SQLite build
        run: make test_framework_GRDBCustomSQLiteOSX
  SPM:
    name: Test SPM
    runs-on: macOS-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Test SPM
        run: make test_SPM
  XCFramework:
    name: Test XCFramework
    runs-on: macOS-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Test XCFramework archive
        run: make test_archive_GRDBOSX_xcframework
